# Generated by Django 2.1.3 on 2019-09-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.Poliza')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
