# Generated by Django 2.1.3 on 2019-12-17 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    database_operations = [migrations.AlterModelTable('Banner', 'utils_banner')]

    state_operations = [migrations.DeleteModel('Banner')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
