# Generated by Django 2.1.3 on 2020-01-13 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_auto_20191217_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benaccidente',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('CONYUGE', 'Cónyuge'), ('HIJO', 'Hijo'), ('HIJA', 'Hija')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='bensepelio',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('CONYUGE', 'Cónyuge'), ('HIJO', 'Hijo'), ('HIJA', 'Hija')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='perfilempleado',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
