# Generated by Django 2.1.3 on 2019-09-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='benaccidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.benAccidente'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='bensepelio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.benSepelio'),
        ),
    ]
