# Generated by Django 2.1.3 on 2020-01-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_auto_20200122_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de constitución'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
