# Generated by Django 2.1.3 on 2019-10-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_auto_20190909_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='motivo',
            field=models.CharField(blank=True, choices=[('1', 'Por venta'), ('2', 'Ya no quiero mi seguro'), ('3', 'Cancelación de prestamo')], max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='perfilempleado',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.Entidad'),
        ),
    ]
