# Generated by Django 2.1.3 on 2020-01-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_auto_20200113_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cliente', to='cotizador.PerfilEmpleado'),
        ),
    ]
