# Generated by Django 2.1.3 on 2019-11-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_auto_20191017_0402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poliza',
            options={'permissions': (('report_debito_automatico', 'report_debito_automatico'), ('report_cotizaciones', 'report_cotizaciones'), ('reporte_deduccion_nomina', 'reporte_deduccion_nomina'), ('reporte_polizas_vencer', 'reporte_polizas_vencer')), 'verbose_name': 'póliza', 'verbose_name_plural': 'Pólizas Automovil'},
        ),
        # migrations.AddField(
        #     model_name='poliza',
        #     name='fecha_vence',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo_cobertura',
            field=models.CharField(blank=True, choices=[('amplia', 'Cobertura amplia'), ('basica', 'Cobertura básica')], max_length=165, null=True),
        ),
    ]
