# Generated by Django 2.1.3 on 2020-01-22 02:25

import cotizador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_ticket_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='file_carta',
            field=models.FileField(blank=True, null=True, upload_to=cotizador.models.get_media_url),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='file_cedula',
            field=models.FileField(blank=True, null=True, upload_to=cotizador.models.get_media_url),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='file_circulacion',
            field=models.FileField(blank=True, null=True, upload_to=cotizador.models.get_media_url),
        ),
    ]
