# Generated by Django 2.1.3 on 2020-01-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
            ],
            options={
                'verbose_name': 'persona jurídica',
                'verbose_name_plural': 'clientes',
                'proxy': True,
                'indexes': [],
            },
            bases=('cotizador.cliente',),
        ),
        migrations.CreateModel(
            name='ClienteNatural',
            fields=[
            ],
            options={
                'verbose_name': 'persona natural',
                'verbose_name_plural': 'clientes',
                'proxy': True,
                'indexes': [],
            },
            bases=('cotizador.cliente',),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
