# Generated by Django 2.1.3 on 2019-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_auto_20191017_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='tipo_cobertura',
            field=models.CharField(blank=True, choices=[('amplia', 'Cobertura amplia'), ('basica', 'Cobertura básica')], max_length=165, null=True),
        ),
    ]
