# Generated by Django 2.1.3 on 2019-12-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_auto_20191126_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_vence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('debito_automatico', 'Débito automático'), ('deduccion_nomina', 'Deducción de nómina'), ('deposito_referenciado', 'Depósito referenciado')], max_length=25, null=True),
        ),
    ]
