# Generated by Django 2.1.3 on 2020-01-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_auto_20200122_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_expedicion',
        ),
    ]
