# Generated by Django 2.1.3 on 2019-12-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_auto_20191123_1439'),
        ('cotizador', '0006_auto_20191212_0046'),
    ]

    operations = [
    ]
