# Generated by Django 2.1.3 on 2020-01-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_remove_cliente_fecha_expedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
