# Generated by Django 2.1.3 on 2019-12-17 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cotizador', '0007_merge_20191217_1821'),
    ]

    database_operations = [migrations.AlterModelTable('Departamento', 'utils_departamento'),
                           migrations.AlterModelTable('Municipio', 'utils_municipio')]

    state_operations = [migrations.DeleteModel('Departamento'), migrations.DeleteModel('Municipio')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
