# Generated by Django 2.1.3 on 2020-01-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_cliente',
            field=models.PositiveIntegerField(choices=[(1, 'Prospecto'), (2, 'Cliente activo'), (3, 'Cliente inactivo')], default=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.PositiveIntegerField(choices=[(1, 'Persona Natural'), (2, 'Persona Jurídica')], default=1),
        ),
    ]
