# Generated by Django 2.1.3 on 2020-01-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0010_auto_20200122_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_cliente',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Prospecto'), (2, 'Cliente activo'), (3, 'Cliente inactivo')], null=True),
        ),
    ]
