# Generated by Django 2.1.3 on 2020-01-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0011_auto_20200122_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_automovil_cliente', to='cotizador.Cliente'),
        ),
    ]
