# Generated by Django 2.1.3 on 2020-02-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0013_auto_20200202_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
            ],
            options={
                'verbose_name': 'contacto',
                'proxy': True,
                'indexes': [],
            },
            bases=('cotizador.cliente',),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Persona Natural'), (2, 'Persona Jurídica')], default=1),
        ),
    ]
