# Generated by Django 2.1.3 on 2020-02-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0014_auto_20200202_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='contact',
            new_name='contacto',
        ),
    ]
