# Generated by Django 2.1.3 on 2020-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0016_auto_20200202_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='email',
            field=models.EmailField(blank=True, max_length=165, null=True, verbose_name='email de contacto'),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='ruc',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
