# Generated by Django 2.1.3 on 2020-02-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0017_auto_20200203_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.PositiveIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
    ]
