# Generated by Django 2.1.3 on 2020-02-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0019_auto_20200203_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.Ramo'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='sub_ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.SubRamo'),
        ),
    ]
