# Generated by Django 2.1.3 on 2020-02-03 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0020_auto_20200203_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='contratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_automovil_contratante', to='cotizador.Cliente'),
        ),
    ]
