# Generated by Django 2.1.3 on 2020-02-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0021_poliza_contratante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
