# Generated by Django 2.1.3 on 2020-02-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0022_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.Grupo'),
        ),
    ]
