# Generated by Django 2.1.3 on 2020-02-03 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0024_auto_20200203_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='nombre')),
                ('label', models.CharField(max_length=65, verbose_name='etiqueta')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_adicionales', to='cotizador.Ramo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'permissions': (('report_debito_automatico', 'report_debito_automatico'), ('report_cotizaciones', 'report_cotizaciones'), ('reporte_deduccion_nomina', 'reporte_deduccion_nomina'), ('reporte_polizas_vencer', 'reporte_polizas_vencer')), 'verbose_name': 'póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='name',
            field=models.CharField(max_length=75, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='tipo_cobertura',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Básica'), (2, 'Amplia'), (3, 'Adicional'), (4, 'Opcional')], default=1, verbose_name='tipo de cobertura'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='tipo_exceso',
            field=models.CharField(choices=[('0.0', '0.0'), ('valor_nuevo', 'Valor de Nuevo'), ('valor_depreciado', 'Valor Depreciado'), ('otro', 'Otro')], default='0.0', max_length=25, verbose_name='variable de referencia'),
        ),
    ]
