# Generated by Django 2.1.3 on 2020-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0025_auto_20200203_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='f_pago',
            field=models.PositiveIntegerField(choices=[(1, 'Contado'), (2, 'Credito')], null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (4, 'Nomina'), (5, 'Pestamos'), (6, 'Tarjeta de Credito')], null=True),
        ),
    ]
