# Generated by Django 2.1.3 on 2020-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0026_auto_20200204_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='amount_comision',
            field=models.FloatField(default=0.0, verbose_name='total comisión'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='per_comision',
            field=models.FloatField(default=0.0, verbose_name='% comisión'),
        ),
    ]
