# Generated by Django 2.1.3 on 2020-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0027_auto_20200204_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='extra_data',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='campos adicionales'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='amount_comision',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total comisión'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='anno',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='costo_exceso',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='cuotas',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='deducible_rotura_vidrios',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='emision',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='f_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Contado'), (2, 'Credito')], null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='forma_pago',
            field=models.CharField(blank=True, default='anual', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='iva',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (4, 'Nomina'), (5, 'Pestamos'), (6, 'Tarjeta de Credito')], null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='marca',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='minimo_deducible',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='minimo_deducible_extension',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='modelo',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='monto_cuota',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='monto_exceso',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='per_comision',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='% comisión'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='porcentaje_deducible',
            field=models.FloatField(blank=True, default=0.2, help_text='usar formato decimar. Ejemplo 0.05 = 5%', null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='porcentaje_deducible_extension',
            field=models.FloatField(blank=True, default=0.3, help_text='usar formato decimar. Ejemplo 0.05 = 5%', null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='subtotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='suma_asegurada',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='valor_nuevo',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
