# Generated by Django 2.1.3 on 2020-02-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0028_auto_20200204_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturaPoliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0.0)),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Cobertura')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Poliza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'ANULADO'), (1, 'VIGENTE'), (2, 'VENCIDO'), (3, 'PAGADO')], null=True),
        ),
    ]
