# Generated by Django 2.1.3 on 2020-02-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0029_auto_20200205_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha_vence',
            field=models.DateField(blank=True, null=True),
        ),
    ]
