# Generated by Django 2.1.3 on 2020-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0030_auto_20200205_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='descuento',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='otros',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
