# Generated by Django 2.1.3 on 2020-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0031_auto_20200205_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='f_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Contado'), (2, 'Credito')], null=True, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (4, 'Nomina'), (5, 'Pestamos'), (6, 'Tarjeta de Credito')], null=True, verbose_name='pago referenciado'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='no_poliza',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='no_recibo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
