# Generated by Django 2.1.3 on 2020-02-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0032_auto_20200206_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='segundo apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='primer apellido'),
        ),
    ]
