# Generated by Django 2.1.3 on 2020-02-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0033_auto_20200219_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='estado_poliza',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Activa'), (2, 'Vencida'), (3, 'Renovada'), (4, 'Cancelada'), (5, 'Anulada'), (6, 'Otro')], null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_cliente',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Prospecto'), (2, 'Activo'), (3, 'Inactivo')], null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='f_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Contado'), (2, 'Cŕedito')], null=True, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo_cobertura',
            field=models.CharField(blank=True, choices=[(1, 'Básica'), (2, 'Amplia'), (3, 'Adicional'), (4, 'Opcional')], max_length=165, null=True),
        ),
    ]
