# Generated by Django 2.1.3 on 2020-02-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0034_auto_20200219_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Union de hecho libre')], null=True),
        ),
    ]
