# Generated by Django 2.1.3 on 2020-02-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0035_cliente_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='tipo_poliza',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Colectiva')], default=1, null=True),
        ),
    ]
