# Generated by Django 2.1.3 on 2020-02-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0036_poliza_tipo_poliza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado_poliza',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Activa'), (2, 'Vencida'), (3, 'Renovada'), (4, 'Cancelada'), (5, 'Anulada'), (6, 'Otro')], default=1, null=True),
        ),
    ]
