# Generated by Django 2.1.3 on 2020-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0038_cliente_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='número de identificación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='número de identificación'),
        ),
    ]
