# Generated by Django 2.1.3 on 2020-02-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0039_auto_20200219_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_representante_legal', to='cotizador.Cliente'),
        ),
    ]
