# Generated by Django 2.1.3 on 2020-02-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0040_cliente_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campoadicional',
            name='ramo',
        ),
        migrations.AddField(
            model_name='campoadicional',
            name='sub_ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_tecnicos', to='cotizador.SubRamo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cédula'), (2, 'Pasaporte'), (3, 'Cédula de residente'), (4, 'Otro')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='f_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Contado'), (2, 'Fraccionado')], null=True, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de inicio vigencia'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha_vence',
            field=models.DateField(blank=True, null=True, verbose_name='fecha fin de vigencia'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='no_poliza',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='número de póliza'),
        ),
    ]
