# Generated by Django 2.1.3 on 2020-02-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0041_auto_20200221_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoPoliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.CharField(blank=True, max_length=10000, null=True, verbose_name='datos técnicos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='extra_data',
        ),
        migrations.AlterField(
            model_name='poliza',
            name='cesion_derecho',
            field=models.BooleanField(default=False, verbose_name='¿tiene cesión de derecho?'),
        ),
        migrations.AddField(
            model_name='datopoliza',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Poliza'),
        ),
    ]
