# Generated by Django 2.1.3 on 2020-02-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0042_auto_20200225_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datopoliza',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_tecnicos', to='cotizador.Poliza'),
        ),
    ]
