# Generated by Django 2.1.3 on 2020-02-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0044_auto_20200225_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_cesionario',
            field=models.BooleanField(default=False),
        ),
    ]
