# Generated by Django 2.1.3 on 2020-02-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0045_cliente_es_cesionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cesioinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.Cliente'),
        ),
    ]
