# Generated by Django 2.1.3 on 2020-02-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cotizador', '0046_poliza_cesioinario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('tiene_caducidad', models.BooleanField(default=False)),
                ('fecha_caducidad', models.DateField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('key', models.PositiveIntegerField(null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
