# Generated by Django 2.1.3 on 2020-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0049_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='concepto',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
