# Generated by Django 2.1.3 on 2020-02-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0050_poliza_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estado_poliza',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pendiente'), (1, 'Activa'), (2, 'Vencida'), (3, 'Renovada'), (4, 'Cancelada'), (5, 'Anulada'), (6, 'Otro')], default=0, null=True),
        ),
    ]
