# Generated by Django 2.1.3 on 2020-02-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0051_auto_20200226_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.Moneda'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='suma_asegurada',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='suma asegurada total'),
        ),
    ]
