# Generated by Django 2.1.3 on 2020-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0053_comentario_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='concepto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='actividad económica'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='página web'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='teléfono'),
        ),
    ]
