# Generated by Django 2.1.3 on 2020-03-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0054_auto_20200303_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='concepto',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nueva Póliza'), (2, 'Renovación')], default=1, null=True),
        ),
    ]
