# Generated by Django 2.1.3 on 2020-03-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0055_poliza_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Anulado'), (1, 'Vigente'), (2, 'Vencido'), (3, 'Pagado')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cotizador.Poliza'),
        ),
    ]
