# Generated by Django 2.1.3 on 2020-01-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import trustseguros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0002_banner'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('tiene_caducidad', models.BooleanField(default=False)),
                ('fecha_caducidad', models.DateField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('key', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('ruc', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(max_length=8, null=True)),
                ('direccion', models.TextField(max_length=250, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=45, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Departamento')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='aseguradoraSubRamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.0)),
                ('aseguradora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Aseguradora')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beneficiario', models.CharField(max_length=100, null=True)),
                ('primer_nombre', models.CharField(max_length=45, null=True)),
                ('segundo_nombre', models.CharField(max_length=45, null=True)),
                ('primer_apellido', models.CharField(max_length=45, null=True)),
                ('segundo_apellido', models.CharField(max_length=45, null=True)),
                ('tipo_identificacion', models.CharField(max_length=45, null=True)),
                ('numero_identificacion', models.CharField(max_length=45, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='calendarioPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(null=True)),
                ('fecha_pago', models.DateField(null=True)),
                ('valor_pago', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'campaña',
            },
        ),
        migrations.CreateModel(
            name='catalogoArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('edificio', 'Edificio'), ('auto', 'Automovil'), ('persona', 'Persona')], max_length=65, null=True)),
                ('suma_asegurada', models.FloatField(default=0.0)),
                ('ubicacion', models.TextField(blank=True, max_length=500, null=True)),
                ('marca', models.CharField(blank=True, max_length=65, null=True)),
                ('modelo', models.CharField(blank=True, max_length=65, null=True)),
                ('placa', models.CharField(blank=True, max_length=65, null=True)),
                ('anno', models.CharField(blank=True, max_length=65, null=True)),
                ('motor', models.CharField(blank=True, max_length=65, null=True)),
                ('chasis', models.CharField(blank=True, max_length=65, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_persona', models.CharField(blank=True, choices=[('titular', 'Titular'), ('dependiente', 'Dependiente')], max_length=60, null=True)),
                ('parentesco', models.CharField(blank=True, choices=[('Papa', 'Papa'), ('Mama', 'Mama'), ('Conyuge', 'Conyuge'), ('Hijo', 'Hijo'), ('Hija', 'Hija')], max_length=65, null=True)),
                ('cedula', models.CharField(blank=True, max_length=14, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cesionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cesionado', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.PositiveIntegerField(blank=True, choices=[(1, 'Cédula nicaraguense'), (2, 'Cédula de residencia'), (3, 'Pasaporte'), (4, 'Registro único de contribuyente')], null=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=8, null=True)),
                ('celular', models.CharField(blank=True, max_length=8, null=True)),
                ('email_principal', models.EmailField(blank=True, max_length=200, null=True)),
                ('email_alterno', models.EmailField(blank=True, max_length=200, null=True)),
                ('correo_poliza_vencer', models.BooleanField(default=False)),
                ('correo_cartera_vencer', models.BooleanField(default=False)),
                ('sms_poliza_vencer', models.BooleanField(default=False)),
                ('sms_cartera_vencer', models.BooleanField(default=False)),
                ('link_accesso', models.CharField(blank=True, max_length=250, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=45, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
                ('actividad_economica', models.CharField(blank=True, max_length=250, null=True)),
                ('pagina_web', models.CharField(blank=True, max_length=250, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Persona Natural'), (2, 'Persona Jurídica')], null=True, verbose_name='Tipo de cliente')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Departamento')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Municipio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, null=True)),
                ('segundo_nombre', models.CharField(max_length=45, null=True)),
                ('primer_apellido', models.CharField(max_length=45, null=True)),
                ('segundo_apellido', models.CharField(max_length=45, null=True)),
                ('telefono', models.CharField(max_length=8, null=True)),
                ('puesto', models.CharField(max_length=45, null=True)),
                ('email_principal', models.EmailField(max_length=200, null=True)),
                ('aseguradora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Aseguradora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endoso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo_prima', models.CharField(max_length=45, null=True)),
                ('tipo_endoso', models.CharField(choices=[('Altas', 'Altas'), ('Bajas', 'Bajas'), ('Aumentos', 'Aumentos'), ('Disminución', 'Disminución'), ('Reclamos', 'Reclamos'), ('Renovaciones', 'Renovaciones'), ('Nueva', 'Nueva')], max_length=45, null=True)),
                ('descripcion', models.TextField(max_length=400, null=True)),
                ('fecha_emision', models.DateField(null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('comision', models.FloatField(default=30.0)),
                ('prima_neta', models.FloatField(default=0.0)),
                ('derecho_emision', models.FloatField(default=0.0)),
                ('bomberos', models.FloatField(default=0.0)),
                ('recargo_descuento', models.FloatField(default=0.0, verbose_name='Recargo/Descuento')),
                ('iva', models.FloatField(default=0.0)),
                ('otros', models.FloatField(default=0.0)),
                ('prima_total', models.FloatField(default=0.0)),
                ('forma_pago', models.CharField(max_length=150, null=True)),
                ('cuotas', models.PositiveSmallIntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, choices=[('proceso', 'En proceso'), ('documentacion', 'Pendiente de documentacion'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], max_length=100, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_expedicion', models.DateField(null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nombre_grupo', models.CharField(max_length=100, null=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Aseguradora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTramite',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='número')),
                ('tipo_tramite', models.CharField(blank=True, choices=[('endoso', 'Endoso'), ('nueva', 'Póliza nueva'), ('renovacion', 'Renovación'), ('cancelacion', 'Cancelación')], max_length=25, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(blank=True, choices=[('proceso', 'En proceso'), ('documentacion', 'Pendiente de documentacion'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], max_length=150, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aseguradora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trustseguros.Aseguradora')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trustseguros.Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tramite',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Colectiva')], default=1, null=True, verbose_name='tipo póliza')),
                ('numero_poliza', models.CharField(max_length=100, null=True, unique=True)),
                ('estado_poliza', models.CharField(choices=[('1', 'Nueva'), ('2', 'Renovada'), ('3', 'No renovada'), ('4', 'Cancelada por no tomada'), ('5', 'Cancelada por falta de pago'), ('6', 'Anulada')], max_length=100, null=True)),
                ('es_renovable', models.BooleanField(default=False)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('beneficiaro_oneroso', models.BooleanField(default=False)),
                ('observaciones_internas', models.TextField(blank=True, max_length=500, null=True)),
                ('observaciones_cliente', models.TextField(blank=True, max_length=500, null=True)),
                ('tipo_moneda', models.PositiveIntegerField(null=True)),
                ('prima_neta', models.FloatField(default=0.0)),
                ('derecho_emision', models.FloatField(default=0.0)),
                ('recargo_descuento', models.FloatField(blank=True, default=0.0)),
                ('iva', models.FloatField(default=0.0)),
                ('otros', models.FloatField(blank=True, default=0.0)),
                ('prima_total', models.FloatField(default=0.0)),
                ('porcentaje_comision', models.FloatField(blank=True, default=0.0)),
                ('monto_comision', models.FloatField(blank=True, default=0.0)),
                ('comision_agencia', models.FloatField(blank=True, default=0.0)),
                ('monto_agencia', models.FloatField(blank=True, default=0.0)),
                ('correo_poliza_vencer', models.BooleanField(default=False)),
                ('correo_cartera_vencer', models.BooleanField(default=False)),
                ('sms_poliza_vencer', models.BooleanField(default=False)),
                ('sms_cartera_vencer', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(max_length=45)),
                ('metodo_pago', models.CharField(max_length=45)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('aseguradora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Aseguradora')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratante_poliza', to='trustseguros.Cliente')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trustseguros.Grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubRamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('ramo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Ramo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='número')),
                ('tipo_tramite', models.CharField(blank=True, choices=[('endoso', 'Endoso'), ('nueva', 'Póliza nueva'), ('renovacion', 'Renovación'), ('cancelacion', 'Cancelación')], max_length=25, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(blank=True, choices=[('proceso', 'En proceso'), ('documentacion', 'Pendiente de documentacion'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], max_length=150, null=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trustseguros.Aseguradora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Cliente')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trustseguros.Poliza')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('porcentaje_comision', models.FloatField(default=0.0)),
                ('porcentaje_sub_comision', models.FloatField(default=0.0)),
                ('porcentaje_retencion', models.FloatField(default=0.0)),
                ('total_comision', models.FloatField(default=0.0)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='poliza',
            name='sub_ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.SubRamo', verbose_name='ramo'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poliza',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Vendedor'),
        ),
        migrations.AddField(
            model_name='historicaltramite',
            name='poliza',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trustseguros.Poliza'),
        ),
        migrations.AddField(
            model_name='historicaltramite',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sub_ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.SubRamo'),
        ),
        migrations.AddField(
            model_name='endoso',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Poliza'),
        ),
        migrations.AddField(
            model_name='endoso',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trustseguros.Tramite'),
        ),
        migrations.AddField(
            model_name='endoso',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cesionario',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Cliente'),
        ),
        migrations.AddField(
            model_name='cesionario',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Poliza'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Poliza'),
        ),
        migrations.AddField(
            model_name='calendariopago',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Poliza'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Cliente'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Poliza'),
        ),
        migrations.AddField(
            model_name='aseguradorasubramo',
            name='sub_ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.SubRamo'),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.Cliente'),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asegurados_poliza', to='trustseguros.Poliza'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trustseguros.catalogoArchivo'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='type',
            field=models.ForeignKey(blank=trustseguros.models.Tramite, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tipo_identificacion', 'numero_identificacion')},
        ),
    ]
