# Generated by Django 2.1.3 on 2020-01-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustseguros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
            ],
            options={
                'verbose_name': 'persona jurídica',
                'verbose_name_plural': 'personas jurídicas',
                'proxy': True,
                'indexes': [],
            },
            bases=('trustseguros.cliente',),
        ),
        migrations.CreateModel(
            name='ClienteNatural',
            fields=[
            ],
            options={
                'verbose_name': 'persona natural',
                'verbose_name_plural': 'personas naturales',
                'proxy': True,
                'indexes': [],
            },
            bases=('trustseguros.cliente',),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_identificacion',
        ),
    ]
