# Generated by Django 2.1.3 on 2020-01-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustseguros', '0002_auto_20200102_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cédula nicaraguense'), (2, 'Cédula de residencia'), (3, 'Pasaporte'), (4, 'RUC')], default=1),
        ),
        # migrations.AlterUniqueTogether(
        #     name='cliente',
        #     unique_together=set(),
        # ),
    ]
