# Generated by Django 2.1.3 on 2020-01-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustseguros', '0003_auto_20200102_0518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
    ]
