# Generated by Django 2.1.3 on 2020-01-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustseguros', '0004_auto_20200102_0525'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tipo_identificacion', 'numero_identificacion')},
        ),
    ]
