# Generated by Django 2.1.3 on 2020-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_auto_20200113_1755'),
        ('trustseguros', '0005_auto_20200102_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCotizador',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'verbose_name': 'póliza'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de constitución'),
        ),
    ]
