# Generated by Django 2.1.3 on 2019-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
