# Generated by Django 2.1.3 on 2019-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0002_auto_20190909_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombres',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
