# Generated by Django 2.1.3 on 2019-09-09 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0003_empleado_nombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.CharField(blank=True, max_length=250, null=True)),
                ('poliza', models.CharField(blank=True, max_length=250, null=True)),
                ('marca', models.CharField(blank=True, max_length=250, null=True)),
                ('placa', models.CharField(blank=True, max_length=250, null=True)),
                ('modelo', models.CharField(blank=True, max_length=250, null=True)),
                ('chasis', models.CharField(blank=True, max_length=250, null=True)),
                ('motor', models.CharField(blank=True, max_length=250, null=True)),
                ('suma', models.FloatField(blank=True, null=True)),
                ('prima', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('inicio', models.CharField(blank=True, max_length=250, null=True)),
                ('fin', models.CharField(blank=True, max_length=250, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migracion.Empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
