# Generated by Django 2.1.3 on 2019-09-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0004_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asegurado', models.CharField(blank=True, max_length=250, null=True)),
                ('cedula', models.CharField(blank=True, max_length=250, null=True)),
                ('fechanacimiento', models.CharField(blank=True, max_length=250, null=True)),
                ('edad', models.CharField(blank=True, max_length=250, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['name']},
        ),
    ]
