# Generated by Django 2.1.3 on 2019-09-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0005_auto_20190910_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidente',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migracion.Empleado'),
        ),
    ]
