# Generated by Django 2.1.3 on 2019-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0007_accidente_titular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepelio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ente', models.CharField(blank=True, max_length=255, null=True)),
                ('asegurado', models.CharField(blank=True, max_length=255, null=True)),
                ('desde', models.CharField(blank=True, max_length=255, null=True)),
                ('hasta', models.CharField(blank=True, max_length=255, null=True)),
                ('nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.CharField(blank=True, max_length=255, null=True)),
                ('suma', models.FloatField(blank=True, null=True)),
                ('prima', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
