# Generated by Django 2.1.3 on 2019-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0008_sepelio'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='cedula',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
