# Generated by Django 2.1.3 on 2019-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0009_auto_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='anno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
