# Generated by Django 2.1.3 on 2019-09-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0010_auto_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepelio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='migracion.Empleado'),
        ),
    ]
