# Generated by Django 2.1.3 on 2019-09-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0011_sepelio_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='noblank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
