# Generated by Django 2.1.3 on 2019-10-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0013_empleado_reversed'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidente',
            name='nombres',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidente',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidente',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accidente',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='migracion.Empleado'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automoviles', to='migracion.Empleado'),
        ),
        migrations.AlterField(
            model_name='sepelio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepelios', to='migracion.Empleado'),
        ),
    ]
