# Generated by Django 2.1.3 on 2019-10-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0014_auto_20191002_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepelio',
            name='nombres',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepelio',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sepelio',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sepelio',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sepelio',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
