# Generated by Django 2.1.3 on 2019-10-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0015_auto_20191002_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepelio',
            name='inverted',
            field=models.BooleanField(default=False),
        ),
    ]
