# Generated by Django 2.1.3 on 2019-10-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0016_sepelio_inverted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepelio',
            name='parentesco',
            field=models.CharField(default='TITULAR', max_length=255),
        ),
    ]
