# Generated by Django 2.1.3 on 2019-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0017_sepelio_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependienteSepelio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('certificado', models.CharField(blank=True, max_length=255, null=True)),
                ('ente', models.CharField(blank=True, max_length=255, null=True)),
                ('certificado_dependiente', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_dependiente', models.CharField(blank=True, max_length=255, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=255, null=True)),
                ('cedula', models.CharField(blank=True, max_length=255, null=True)),
                ('ente_dependiente', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
