# Generated by Django 2.1.3 on 2019-10-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0020_auto_20191002_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependientesepelio',
            name='empleado',
        ),
    ]
