# Generated by Django 2.1.3 on 2019-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0021_remove_dependientesepelio_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepelio',
            name='cedula',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
