# Generated by Django 2.1.3 on 2019-12-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion', '0022_sepelio_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
