# Generated by Django 2.1.3 on 2020-03-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contactoaseguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoaseguradora',
            name='aseguradora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Aseguradora'),
        ),
    ]
