# Generated by Django 2.1.3 on 2020-03-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_contactoaseguradora_aseguradora'),
    ]

    operations = [
        migrations.RenameModel('Ticket', 'Tramite')
    ]
