# Generated by Django 2.1.3 on 2020-03-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200324_1740'),
    ]

    operations = [
        migrations.RenameField('Poliza', 'ticket', 'tramite'),
        migrations.RenameField('benSepelio', 'ticket', 'tramite'),
        migrations.RenameField('benAccidente', 'ticket', 'tramite'),
    ]
