# Generated by Django 2.1.3 on 2020-03-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_tramite_tipo_tramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Grupo'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Ramo'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='sub_ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.SubRamo'),
        ),
    ]
