# Generated by Django 2.1.3 on 2020-03-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_tramite_contacto_aseguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
