# Generated by Django 2.1.3 on 2020-03-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200324_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='aseguradora',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='ramo',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='sub_ramo',
        ),
    ]
