# Generated by Django 2.1.3 on 2020-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200324_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='perdir_comentarios',
            field=models.BooleanField(default=False),
        ),
    ]
