# Generated by Django 2.1.3 on 2020-03-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_poliza_pedir_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='emision',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fechahora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='iva',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='prioridad',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='subtotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='suma_asegurada',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='valor_nuevo',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
