# Generated by Django 2.1.3 on 2020-03-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200326_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='medio_solicitud',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Por corredo'), (2, 'En físico')], null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='solicitado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
