# Generated by Django 2.1.3 on 2020-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200326_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='genera_endoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='medio_solicitud',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Por correo'), (2, 'En físico')], null=True),
        ),
    ]
