# Generated by Django 2.1.3 on 2020-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200326_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
