# Generated by Django 2.1.3 on 2020-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_tramite_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='editable',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='pedir_soporte',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='perdir_comentarios',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
