# Generated by Django 2.1.3 on 2020-03-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20200328_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'ordering': ['fecha_vence']},
        ),
        migrations.AddField(
            model_name='pago',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_tramites', to='backend.Tramite'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='backend.Poliza'),
        ),
    ]
