# Generated by Django 2.1.3 on 2020-03-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200328_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cancelando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poliza',
            name='modificando',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_polizas', to='backend.Poliza'),
        ),
    ]
