# Generated by Django 2.1.3 on 2020-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_cotizadorconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizadorconfig',
            options={'verbose_name': 'configuración', 'verbose_name_plural': 'configuración del cotizador'},
        ),
        migrations.AddField(
            model_name='cotizadorconfig',
            name='email_trust',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
