# Generated by Django 2.1.3 on 2020-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20200329_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizadorconfig',
            name='email_accidente',
            field=models.CharField(default='luis.collado@mapfre.com.ni,', max_length=300, verbose_name='Lista de correos de accidente usados para las notificaciones del sistema'),
        ),
    ]
