# Generated by Django 2.1.3 on 2020-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200329_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='procedencia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Trustseguros'), (2, 'Cotizador'), (3, 'Bancaseguros')], null=True),
        ),
    ]
