# Generated by Django 2.1.3 on 2020-03-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_poliza_procedencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldmap_type', models.PositiveSmallIntegerField(choices=[(1, 'Automovil'), (2, 'Sepelio'), (3, 'Accidente'), (4, 'Vida')])),
                ('origin_field', models.CharField(max_length=200)),
                ('destiny_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CampoAdicional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
