# Generated by Django 2.1.3 on 2020-03-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_fieldmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmap',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.CotizadorConfig'),
        ),
    ]
