# Generated by Django 2.1.3 on 2020-03-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20200330_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmap',
            name='destiny_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.CampoAdicional'),
        ),
        migrations.AlterField(
            model_name='fieldmap',
            name='fieldmap_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Automovil'), (2, 'Sepelio'), (3, 'Accidente'), (4, 'Vida')]),
        ),
    ]
