# Generated by Django 2.1.3 on 2020-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20200330_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('En Proceso', 'En Proceso'), ('Pendiente documentación', 'Pendiente documentación'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=55, null=True),
        ),
    ]
