# Generated by Django 2.1.3 on 2020-05-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_cotizadorconfig_email_cobranza'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizadorconfig',
            name='email_renovacion',
            field=models.CharField(default='gcarrion@trustcorreduria.com,', max_length=1000, null=True, verbose_name='Lista de correos adicionales que se incluiran en la notificación del cliente'),
        ),
    ]
