# Generated by Django 2.1.3 on 2020-05-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_cotizadorconfig_email_renovacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizadorconfig',
            name='email_texto',
            field=models.CharField(default='gcarrion@trustcorreduria.com,', max_length=10000, null=True, verbose_name='Contenido del correo'),
        ),
    ]
