# Generated by Django 2.1.3 on 2020-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20200506_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='tipo_cobertura',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Básica'), ('2', 'Amplia'), ('3', 'Adicional'), ('4', 'Opcional')], default=1, verbose_name='tipo de cobertura'),
        ),
        migrations.AlterField(
            model_name='cotizadorconfig',
            name='email_texto',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Contenido del correo'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo_cobertura',
            field=models.CharField(blank=True, choices=[('1', 'Básica'), ('2', 'Amplia'), ('3', 'Adicional'), ('4', 'Opcional')], max_length=165, null=True),
        ),
    ]
