# Generated by Django 2.1.3 on 2020-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20200514_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='solicitudrenovacion',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina')], null=True, verbose_name='medio de pago'),
        ),
    ]
