# Generated by Django 2.1.3 on 2020-06-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_auto_20200606_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poliza',
            options={'ordering': ['fecha_vence'], 'permissions': (('trust_clientes_natural', 'Clientes Naturales'), ('trust_clientes_juridico', 'Clientes Jurídicos'), ('trust_polizas_poliza', 'Pólizas'), ('trust_polizas_tramite', 'Trámites'), ('trust_catalogos_aseguradora', 'Catálogos Aseguradoras'), ('trust_catalogos_grupo', 'Catálogos Grupos'), ('trust_catalogos_ramo', 'Catálogos Ramos'), ('trust_catalogos_subramo', 'Catálogos Sub Ramos'), ('trust_cotizador_empresa', 'Cotizador Empresas Afiliadas'), ('trust_cotizador_marca', 'Cotizador Marcas con Recargo'), ('trust_usuarios_usuario', 'Administrar Usuarios'), ('trust_usuarios_grupo', 'Perfiles y Roles')), 'verbose_name': 'póliza', 'verbose_name_plural': 'Pólizas'},
        ),
    ]
