# Generated by Django 2.1.3 on 2020-06-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_aseguradora_exceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='anno',
            name='aseguradora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depreciacion_anno', to='backend.Aseguradora'),
        ),
    ]
