# Generated by Django 2.1.3 on 2020-06-06 17:39

from django.db import migrations
from backend.models import Anno


def fill_aseguradora_on_annos(apps, schema_editor):
    for anno in Anno.objects.all():
        anno.aseguradora = anno.depreciacion.aseguradora
        anno.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_anno_aseguradora'),
    ]

    operations = [
        migrations.RunPython(fill_aseguradora_on_annos)
    ]
