# Generated by Django 2.1.3 on 2020-06-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
        ('backend', '0048_auto_20200606_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('no_poliza', models.CharField(blank=True, max_length=25, null=True, verbose_name='número de póliza')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'No gestionado'), (2, 'Cotizado'), (3, 'Contactado'), (4, 'En emisión'), (5, 'Vendido'), (6, 'No vendido')], default=1)),
                ('aseguradoras', models.ManyToManyField(to='backend.Aseguradora', verbose_name='aseguradoras')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.TextField(blank=True, max_length=400, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='teléfono')),
                ('cedula', models.CharField(blank=True, max_length=14, null=True, verbose_name='número de identificación')),
                ('primer_nombre', models.CharField(blank=True, max_length=125, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=125, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=125, null=True, verbose_name='primer apellido')),
                ('apellido_materno', models.CharField(blank=True, max_length=125, null=True, verbose_name='segundo apellido')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('celular', models.CharField(blank=True, max_length=8, null=True)),
                ('email_personal', models.EmailField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles')),
                ('estado_civil', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Union de hecho libre')], null=True)),
                ('cropping', image_cropping.fields.ImageRatioField('foto', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('nombre', models.CharField(blank=True, max_length=600, null=True)),
                ('tipo_identificacion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cédula'), (2, 'Pasaporte'), (3, 'Cédula de residente'), (4, 'Otro')], default=1, null=True)),
                ('tipo_cliente', models.PositiveIntegerField(blank=True, choices=[(1, 'Persona Natural'), (2, 'Persona Jurídica')], default=1)),
                ('estado_cliente', models.PositiveIntegerField(blank=True, choices=[(1, 'Prospecto'), (2, 'Activo'), (3, 'Inactivo')], null=True)),
                ('cambiar_pass', models.BooleanField(default=False, verbose_name='Exigir cambio de contraseña')),
                ('sucursal', models.CharField(blank=True, max_length=125, null=True)),
                ('codigo_empleado', models.CharField(blank=True, max_length=25, null=True)),
                ('cargo', models.CharField(blank=True, max_length=125, null=True)),
                ('es_cesionario', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_contacto_referencia', to='backend.Prospect')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_departamento', to='utils.Departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_empresa_referencia', to='backend.Prospect')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Entidad')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_municipio', to='utils.Municipio')),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_representante_legal', to='backend.Prospect')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='oportunity',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Prospect', verbose_name='prospecto'),
        ),
        migrations.AddField(
            model_name='oportunity',
            name='ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Ramo'),
        ),
        migrations.AddField(
            model_name='oportunity',
            name='sub_ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.SubRamo'),
        ),
    ]
