# Generated by Django 2.1.3 on 2020-06-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunity',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Linea', verbose_name='linea'),
        ),
    ]
