# Generated by Django 2.1.3 on 2020-06-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_auto_20200608_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Prospect', verbose_name='prospecto'),
        ),
    ]
