# Generated by Django 2.1.3 on 2020-06-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_remove_oportunity_aseguradoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunityQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emision', models.FloatField(default=0.0)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Aseguradora')),
                ('oportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Oportunity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
