# Generated by Django 2.1.3 on 2020-06-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_oportunityquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunity',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Aseguradora'),
        ),
    ]
