# Generated by Django 2.1.3 on 2020-06-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_auto_20200616_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=65)),
                ('modelo', models.CharField(max_length=65)),
                ('exceso', models.FloatField(default=6.666, verbose_name='Porcentaje Exceso')),
                ('tarifa', models.FloatField(default=11.0, verbose_name='Tarifa por millar')),
                ('coaseguro_robo', models.FloatField(default=20.0, verbose_name='Coaseguro robo')),
                ('coaseguro_dano', models.FloatField(default=20.0, verbose_name='Coaseguro daño')),
                ('deducible', models.FloatField(default=100.0, verbose_name='Mínimo deducible')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa_aseguradora_referencia', to='backend.Aseguradora')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
