# Generated by Django 2.1.3 on 2020-06-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_auto_20200616_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='rc_exceso',
            field=models.BooleanField(default=False, verbose_name='RC en exceso'),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='valor_exceso',
            field=models.FloatField(default=0.0, verbose_name='Valor exceso'),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='valor_nuevo',
            field=models.FloatField(default=0.0, verbose_name='Valor de nuevo'),
        ),
    ]
