# Generated by Django 2.1.3 on 2020-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_auto_20200616_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunityquotation',
            name='coaseguro_dano',
            field=models.FloatField(null=True, verbose_name='Coaseguro daño'),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='coaseguro_robo',
            field=models.FloatField(null=True, verbose_name='Coaseguro robo'),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='deducible',
            field=models.FloatField(null=True, verbose_name='Mínimo deducible'),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='exceso',
            field=models.FloatField(null=True, verbose_name='Porcentaje Exceso'),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='tarifa',
            field=models.FloatField(null=True, verbose_name='Tarifa por millar'),
        ),
        migrations.AlterField(
            model_name='oportunityquotation',
            name='emision',
            field=models.FloatField(null=True, verbose_name='Derecha de emision'),
        ),
    ]
