# Generated by Django 2.1.3 on 2020-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_auto_20200616_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='rc_exceso',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='RC en exceso'),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='valor_exceso',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valor exceso'),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='valor_nuevo',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valor de nuevo'),
        ),
    ]
