# Generated by Django 2.1.3 on 2020-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_oportunity_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunityquotation',
            name='anno',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='marca',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='modelo',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='suma_asegurada',
            field=models.FloatField(null=True, verbose_name='Derecha de emision'),
        ),
    ]
