# Generated by Django 2.1.3 on 2020-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_auto_20200619_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunityquotation',
            name='monto_exceso',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Porcentaje Exceso'),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='valor_exceso',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Porcentaje Exceso'),
        ),
        migrations.AlterField(
            model_name='oportunityquotation',
            name='exceso',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Tarifa Exceso'),
        ),
    ]
