# Generated by Django 2.1.3 on 2020-06-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_auto_20200621_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunityquotation',
            name='suma_asegurada',
        ),
    ]
