# Generated by Django 2.1.3 on 2020-06-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_remove_oportunityquotation_suma_asegurada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together={('aseguradora', 'marca', 'modelo')},
        ),
    ]
