# Generated by Django 2.1.3 on 2020-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_aseguradora_emision_soa'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunity',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Número'),
        ),
    ]
