# Generated by Django 2.1.3 on 2020-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_oportunity_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunity',
            name='fecha_vence',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento'),
        ),
    ]
