# Generated by Django 2.1.3 on 2020-06-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_auto_20200625_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunity',
            name='aseguradora',
        ),
    ]
