# Generated by Django 2.1.3 on 2020-06-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_remove_oportunity_aseguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunity',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
