# Generated by Django 2.1.3 on 2020-06-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_auto_20200626_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobertura',
            name='en_cotizacion',
        ),
    ]
