# Generated by Django 2.1.3 on 2020-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_remove_cobertura_en_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobertura',
            name='en_cotizacion',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Si')], default=0),
        ),
    ]
