# Generated by Django 2.1.3 on 2020-06-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_cobertura_en_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='active',
            field=models.BooleanField(default=False, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='causal',
            field=models.CharField(blank=True, choices=[('A', 'Teléfono Apagado.'), ('B', 'Crédito Cancelado'), ('C', 'Es empleado BANPRO'), ('D', 'Número de Teléfono Equivocado.'), ('E', 'Teléfono fuera de Área / Cobertura.'), ('F', 'Fuera del país.'), ('G', 'No Contesta Teléfono.'), ('H', 'No hay información.'), ('I', 'Presentará Externa Cartera Directa.'), ('J', ' Presentará Externa Corredor.'), ('K', 'Seguro Comparativo.'), ('L', 'Ilocalizable.'), ('M', 'VIP')], max_length=1, null=True, verbose_name='Razón por la que no se concretó la venta'),
        ),
    ]
