# Generated by Django 2.1.3 on 2020-06-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_auto_20200626_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='oportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Oportunity'),
        ),
    ]
