# Generated by Django 2.1.3 on 2020-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_auto_20200721_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='poliza_no',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Número de póliza'),
        ),
    ]
