# Generated by Django 2.1.3 on 2020-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_auto_20200725_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='no_recibo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='número de recibo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de cuota'),
        ),
    ]
