# Generated by Django 2.1.3 on 2020-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_auto_20200725_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_pagado',
            field=models.FloatField(default=0.0),
        ),
    ]
