# Generated by Django 2.1.3 on 2020-07-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_pago_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='medio_pago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Efectivo'), (2, 'Cheque'), (3, 'Crédito'), (4, 'Débito')], default=1, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_pagado',
            field=models.FloatField(default=0.0, verbose_name='monto a recaudar'),
        ),
        migrations.AlterField(
            model_name='solicitudrenovacion',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Efectivo'), (2, 'Cheque'), (3, 'Crédito'), (4, 'Débito')], null=True, verbose_name='medio de pago'),
        ),
    ]
