# Generated by Django 2.1.3 on 2020-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_auto_20200726_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_comision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo_poliza',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Colectiva'), (3, 'Oficio')], default=1, null=True),
        ),
    ]
