# Generated by Django 2.1.3 on 2020-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_pago_fecha_pago_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='referencia de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago_comision',
            field=models.DateField(null=True, verbose_name='Fecha de pago comisión'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_comision',
            field=models.FloatField(default=0.0, verbose_name='Monto de comisión'),
        ),
    ]
