# Generated by Django 2.1.3 on 2020-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20200730_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='causal',
            field=models.CharField(blank=True, choices=[('A', 'Teléfono Apagado.'), ('B', 'Crédito Cancelado'), ('C', 'Es empleado BANPRO'), ('D', 'Número de Teléfono Equivocado.'), ('E', 'Teléfono fuera de Área / Cobertura.'), ('F', 'Fuera del país.'), ('G', 'No Contesta Teléfono.'), ('H', 'No hay información.'), ('I', 'Presentará Externa Cartera Directa.'), ('J', ' Presentará Externa Corredor.'), ('K', 'Seguro Comparativo.'), ('L', 'Ilocalizable.'), ('M', 'VIP'), ('N', 'Póliza interna')], max_length=1, null=True, verbose_name='Razón por la que no se concretó la venta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='medio_pago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], default=6, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='solicitudrenovacion',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], null=True, verbose_name='medio de pago'),
        ),
    ]
