# Generated by Django 2.1.3 on 2020-08-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20200730_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[(None, '---------'), ('Registrado', 'Registrado'), ('Enviado', 'Enviado'), ('Liquidado', 'Liquidado'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado')], default='Registrado', max_length=55, null=True)),
                ('tipo_movimiento', models.CharField(blank=True, choices=[(None, '---------'), ('Reembolso de Gastos', 'Reembolso de Gastos'), ('Choque', 'Choque'), ('Otro', 'Otro')], default='Reembolso de Gastos', max_length=55, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='número')),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=600, null=True)),
                ('fecha_envio_trust', models.DateField(blank=True, null=True, verbose_name='fecha envío a aseguradora')),
                ('tramite_aseguradora', models.CharField(blank=True, max_length=20, null=True, verbose_name='Trámite Aseguradora')),
                ('siniestro_aseguradora', models.CharField(blank=True, max_length=20, null=True, verbose_name='Siniestro Aseguradora')),
                ('fecha_recepcion_aseguradora', models.DateField(blank=True, null=True, verbose_name='fecha recepción aseguradora')),
                ('diagnostico', models.TextField(blank=True, max_length=600, null=True)),
                ('gastos_presentados', models.TextField(blank=True, max_length=600, null=True)),
                ('no_cubierto', models.TextField(blank=True, max_length=600, null=True)),
                ('deducible', models.FloatField(default=0.0, verbose_name='Deducible')),
                ('coaseguro', models.FloatField(default=0.0, verbose_name='Coaseguro')),
                ('monto_pago', models.FloatField(default=0.0, verbose_name='Monto a pagar')),
                ('forma_pago', models.PositiveIntegerField(blank=True, choices=[(1, 'Efectivo'), (2, 'Cheque'), (3, 'Crédito'), (4, 'Débito')], null=True, verbose_name='Forma de pago')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_siniestro', to='backend.Cliente')),
                ('contacto_aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ContactoAseguradora')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_siniestro', to='backend.Poliza')),
            ],
            options={
                'verbose_name': 'Siniestro',
            },
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='causal',
            field=models.CharField(blank=True, choices=[('A', 'Teléfono Apagado.'), ('B', 'Crédito Cancelado'), ('C', 'Es empleado BANPRO'), ('D', 'Número de Teléfono Equivocado.'), ('E', 'Teléfono fuera de Área / Cobertura.'), ('F', 'Fuera del país.'), ('G', 'No Contesta Teléfono.'), ('H', 'No hay información.'), ('I', 'Presentará Externa Cartera Directa.'), ('J', ' Presentará Externa Corredor.'), ('K', 'Seguro Comparativo.'), ('L', 'Ilocalizable.'), ('M', 'VIP'), ('N', 'Póliza interna')], max_length=1, null=True, verbose_name='Razón por la que no se concretó la venta'),
        ),
    ]
