# Generated by Django 2.1.3 on 2020-08-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_auto_20200812_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siniestros',
            name='hora',
        ),
    ]
