# Generated by Django 2.1.3 on 2020-08-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_auto_20200826_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pago',
            new_name='Cuota',
        ),
    ]
