# Generated by Django 2.1.3 on 2020-08-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_auto_20200826_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0.0)),
                ('referencia_pago', models.CharField(blank=True, max_length=65, null=True, verbose_name='referencia de pago')),
                ('medio_pago', models.PositiveSmallIntegerField(choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depositos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], default=6, verbose_name='medio de pago')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='medio_pago',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='referencia_pago',
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cuota'),
        ),
    ]
