# Generated by Django 2.1.3 on 2020-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_auto_20200813_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestros',
            name='coaseguro',
            field=models.FloatField(default=0.0, verbose_name='Coaseguro'),
        ),
        migrations.AlterField(
            model_name='siniestros',
            name='deducible',
            field=models.FloatField(default=0.0, verbose_name='Deducible'),
        ),
        migrations.AlterField(
            model_name='siniestros',
            name='monto_pago',
            field=models.FloatField(default=0.0, verbose_name='Monto a pagar'),
        ),
    ]
