# Generated by Django 2.1.3 on 2020-08-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_auto_20200813_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiniestroTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_siniestro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Trámite Aseguradora')),
                ('monto_reclamo', models.FloatField(default=0.0, verbose_name='Monto Reclamado')),
                ('deducible', models.FloatField(default=0.0, verbose_name='Deducible')),
                ('coaseguro', models.FloatField(default=0.0, verbose_name='Coaseguro')),
                ('gastos_presentados', models.TextField(blank=True, max_length=600, null=True)),
                ('no_cubierto', models.TextField(blank=True, max_length=600, null=True)),
                ('monto_pago', models.FloatField(default=0.0, verbose_name='Monto a pagar')),
                ('forma_pago', models.PositiveIntegerField(blank=True, choices=[(1, 'Efectivo'), (2, 'Cheque'), (3, 'Crédito'), (4, 'Débito')], null=True, verbose_name='Forma de pago')),
                ('diagnostico', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='coaseguro',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='deducible',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='gastos_presentados',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='monto_pago',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='no_cubierto',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='tramite_aseguradora',
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='siniestros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='backend.Siniestros'),
        ),
    ]
