# Generated by Django 2.1.3 on 2020-08-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_auto_20200827_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='monto_pagado',
        ),
    ]
