# Generated by Django 2.1.3 on 2020-08-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0103_auto_20200821_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestrotramite',
            name='forma_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Efectivo'), (2, 'Cheque'), (3, 'Crédito'), (4, 'Débito')], default=1, null=True, verbose_name='Forma de pago'),
        ),
    ]
