# Generated by Django 2.1.3 on 2020-09-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_auto_20200902_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poliza',
            old_name='cuotas',
            new_name='cantidad_cuotas',
        ),
    ]
