# Generated by Django 2.1.3 on 2020-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_remove_siniestrotramite_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestrotramite',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('Efectivo', 'Efectivo'), ('Cheque', 'Cheque'), ('Deposito', 'Deposito'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=55, null=True),
        ),
    ]
