# Generated by Django 2.1.3 on 2020-08-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_siniestrotramite_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestros',
            name='asegurado_certificado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Asegurado / Certificado'),
        ),
    ]
