# Generated by Django 2.1.3 on 2020-09-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_auto_20200904_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='cuotas',
            new_name='cantidad_cuotas',
        ),
    ]
