# Generated by Django 2.1.3 on 2020-09-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0107_auto_20200904_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='comision',
            field=models.FloatField(default=0.0),
        ),
    ]
