# Generated by Django 2.1.3 on 2020-08-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0107_siniestros_asegurado_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestros',
            name='tramite_por_siniestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramite_por_siniestro', to='backend.SiniestroTramite', verbose_name='Tramite siniestro'),
        ),
    ]
