# Generated by Django 2.1.3 on 2020-09-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0108_siniestros_tramite_por_siniestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(blank=True, choices=[(None, '---------'), ('Registrado', 'Registrado'), ('Enviado', 'Enviado'), ('Liquidado', 'Liquidado'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado')], default='Registrado', max_length=55, null=True)),
                ('tipo_movimiento', models.CharField(blank=True, choices=[(None, '---------'), ('Reembolso de Gastos', 'Reembolso de Gastos'), ('Choque', 'Choque'), ('Otro', 'Otro')], default='Reembolso de Gastos', max_length=55, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='número')),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('asegurado_certificado', models.CharField(blank=True, max_length=30, null=True, verbose_name='Asegurado / Certificado')),
                ('descripcion', models.TextField(blank=True, max_length=600, null=True)),
                ('fecha_envio_trust', models.DateField(blank=True, null=True, verbose_name='fecha envío a aseguradora')),
                ('siniestro_aseguradora', models.CharField(blank=True, max_length=20, null=True, verbose_name='Siniestro Aseguradora')),
                ('fecha_recepcion_aseguradora', models.DateField(blank=True, null=True, verbose_name='fecha recepción aseguradora')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_siniestro', to='backend.Cliente')),
                ('contacto_aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ContactoAseguradora')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_siniestro', to='backend.Poliza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='contacto_aseguradora',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='poliza',
        ),
        migrations.RemoveField(
            model_name='siniestros',
            name='tramite_por_siniestro',
        ),
        migrations.RemoveField(
            model_name='siniestrotramite',
            name='siniestros',
        ),
        migrations.DeleteModel(
            name='Siniestros',
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramite_seleccionado', to='backend.SiniestroTramite'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='siniestro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='backend.Siniestro'),
        ),
    ]
