# Generated by Django 2.1.3 on 2020-09-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0108_pagocuota_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='fecha_pago_comision',
            field=models.DateField(null=True),
        ),
    ]
