# Generated by Django 2.1.3 on 2020-09-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0109_auto_20200907_1129'),
        ('backend', '0109_pagocuota_fecha_pago_comision'),
    ]

    operations = [
    ]
