# Generated by Django 2.1.3 on 2020-09-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0110_merge_20200907_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='actividad económica'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de constitución'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='página web'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='razon_social',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='ruc',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='número de identificación'),
        ),
    ]
