# Generated by Django 2.1.3 on 2020-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0111_auto_20200920_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizadorconfig',
            name='email_cesion_derecho',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Lista de correos adicionales que se incluiran en caso de cesiones de derecho'),
        ),
    ]
