# Generated by Django 2.1.3 on 2020-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0112_cotizadorconfig_email_cesion_derecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='autorenovacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cédula'), (2, 'Pasaporte'), (3, 'Cédula de residente'), (4, 'Otro'), (5, 'RUC')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago_comision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago comisión'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='tipo_identificacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cédula'), (2, 'Pasaporte'), (3, 'Cédula de residente'), (4, 'Otro'), (5, 'RUC')], default=1, null=True),
        ),
    ]
