# Generated by Django 2.1.3 on 2020-10-12 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0113_auto_20201005_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siniestro',
            name='asegurado_certificado',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='code',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='contacto_aseguradora',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='fecha_envio_trust',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='fecha_recepcion',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='fecha_recepcion_aseguradora',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='siniestro_aseguradora',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='tipo_movimiento',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='tramite',
        ),
        migrations.RemoveField(
            model_name='siniestrotramite',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='siniestrotramite',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='siniestrotramite',
            name='monto_pago',
        ),
        migrations.RemoveField(
            model_name='siniestrotramite',
            name='siniestro',
        ),
        migrations.RemoveField(
            model_name='siniestrotramite',
            name='tramite_siniestro',
        ),
        migrations.AddField(
            model_name='siniestro',
            name='deducible_aplicado',
            field=models.FloatField(default=0.0, verbose_name='Deducible aplicado'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='deducible_pendiente',
            field=models.FloatField(default=0.0, verbose_name='Deducible pendiente'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha liquidacion'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('Efectivo', 'Efectivo'), ('Cheque', 'Cheque'), ('Deposito', 'Deposito'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='gastos_presentados',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='detalles gastos'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='monto_pagado',
            field=models.FloatField(default=0.0, verbose_name='Total Reclamado'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='no_cubierto',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='reclamo_aseguradora',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numero reclamo'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_siniestro', to='backend.Cliente'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='contacto_aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ContactoAseguradora'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='descripcion',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='estado',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('Registrado', 'Registrado'), ('Enviado', 'Enviado'), ('Liquidado', 'Liquidado'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado')], default='Registrado', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='fecha_envio_trust',
            field=models.DateField(blank=True, null=True, verbose_name='fecha envío a aseguradora'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='fecha_recepcion_aseguradora',
            field=models.DateField(blank=True, null=True, verbose_name='fecha recepción aseguradora'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='fecha registro'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='fecha_suceso',
            field=models.DateField(blank=True, null=True, verbose_name='fecha suceso'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='nombre_asegurado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='numero_siniestro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='reclamo aseguradora'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_siniestro', to='backend.Poliza'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='tipo_asegurado',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('Titular', 'Titular'), ('Dependiente', 'Dependiente')], default='Titular', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='tipo_movimiento',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('Reembolso de Gastos', 'Reembolso de Gastos'), ('Choque', 'Choque'), ('Otro', 'Otro')], default='Reembolso de Gastos', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='tramite_aseguradora',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='trámite aseguradora'),
        ),
        migrations.AddField(
            model_name='siniestrotramite',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestro_cliente', to='backend.Cliente'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='estado',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('En Proceso', 'En Proceso'), ('Pagado', 'Pagado'), ('Declinado', 'Declinado')], default='En Proceso', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestro_poliza', to='backend.Poliza'),
        ),
        migrations.AlterField(
            model_name='siniestrotramite',
            name='gastos_presentados',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='detalles de gastos'),
        ),
    ]
