# Generated by Django 2.1.3 on 2020-10-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0114_auto_20201012_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Diagnostico'),
        ),
    ]
