# Generated by Django 2.1.3 on 2020-10-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_siniestro_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='movivo_cancelacion',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'No tomada'), (2, 'Cambio de compañia'), (3, 'Crédito cancelado'), (4, 'Falta de pago'), (5, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='otro_motivo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Especificar motivo'),
        ),
    ]
