# Generated by Django 2.1.3 on 2020-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0116_auto_20201026_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='perdir_motivo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
