# Generated by Django 2.1.3 on 2020-10-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0118_auto_20201026_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
