# Generated by Django 2.1.3 on 2020-10-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0120_aseguradora_emision_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='monto_soa',
            field=models.FloatField(default=55.0, verbose_name='Monto SOA'),
        ),
    ]
