# Generated by Django 2.1.3 on 2020-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0122_auto_20201104_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='ejecutivo',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
