# Generated by Django 2.1.3 on 2020-11-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0123_poliza_ejecutivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='ejecutivo',
        ),
        migrations.AddField(
            model_name='poliza',
            name='comisionista',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='sub comisionista'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='amount_comision_eje',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='total sub comisionista'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='per_comision_eje',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='% sub comisionista'),
        ),
    ]
