# Generated by Django 2.1.3 on 2020-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0125_poliza_ejecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
