# Generated by Django 2.1.3 on 2020-11-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0126_moneda_simbolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='email_notificacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='medio_pago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depósitos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], default=6, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depósitos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='solicitudrenovacion',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depósitos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='m_pago',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depósitos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], null=True, verbose_name='medio de pago'),
        ),
    ]
