# Generated by Django 2.1.3 on 2020-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0127_auto_20201124_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='email_notificacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email para notificaciones'),
        ),
    ]
