# Generated by Django 2.1.3 on 2020-11-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0129_auto_20201124_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='email_notificacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='email para notificaciones'),
        ),
    ]
