# Generated by Django 2.1.3 on 2020-11-24 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0130_auto_20201124_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Linea'),
        ),
        migrations.AlterField(
            model_name='campain',
            name='name',
            field=models.CharField(max_length=125, verbose_name='nombre de la campaña'),
        ),
    ]
