# Generated by Django 2.1.3 on 2020-12-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0132_auto_20201124_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='contenido_correo',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='formato_cotizacion',
        ),
    ]
