# Generated by Django 2.1.3 on 2020-12-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0133_auto_20201201_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='aseguradoras',
            field=models.ManyToManyField(blank=True, to='backend.Aseguradora', verbose_name='Aseguradoras con las que cotiza'),
        ),
    ]
