# Generated by Django 2.1.3 on 2020-12-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0134_linea_aseguradoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunityquotation',
            name='prima',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='suma_asegurada',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Suma asegurada'),
        ),
        migrations.AddField(
            model_name='oportunityquotation',
            name='total',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='oportunityquotation',
            name='emision',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Derecho de emision'),
        ),
    ]
