# Generated by Django 2.1.3 on 2020-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0135_auto_20201201_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='subramo',
            name='show_quotation',
            field=models.BooleanField(default=False, verbose_name='mostrar módulo de cotizacion de automóviles'),
        ),
    ]
