# Generated by Django 2.1.3 on 2020-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0136_subramo_show_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
