# Generated by Django 2.1.3 on 2020-12-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0137_documenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'documento'},
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'ordering': ['fecha_vence'], 'permissions': (('trust_clientes_natural', 'Clientes Naturales(trustseguros)'), ('trust_clientes_juridico', 'Clientes Jurídicos(trustseguros)'), ('trust_polizas_poliza', 'Pólizas(trustseguros)'), ('trust_polizas_tramite', 'Trámites(trustseguros)'), ('trust_catalogos_aseguradora', 'Catálogos Aseguradoras(trustseguros)'), ('trust_catalogos_tarifa', 'Catálogos Tarifas(trustseguros)'), ('trust_catalogos_linea', 'Línea de negocios(trustseguros)'), ('trust_catalogos_campain', 'Campañas(trustseguros)'), ('trust_catalogos_documenttypes', 'Documentos PLD(trustseguros)'), ('trust_catalogos_grupo', 'Catálogos Grupos(trustseguros)'), ('trust_catalogos_ramo', 'Catálogos Ramos(trustseguros)'), ('trust_catalogos_subramo', 'Catálogos Sub Ramos(trustseguros)'), ('trust_cotizador_empresa', 'Cotizador Empresas Afiliadas(trustseguros)'), ('trust_cotizador_marca', 'Cotizador Marcas con Recargo(trustseguros)'), ('trust_usuarios_usuario', 'Administrar Usuarios(trustseguros)'), ('trust_usuarios_grupo', 'Perfiles y Roles(trustseguros)'), ('trust_crm_oportunidad', 'CRM Oportunidades(trustseguros)'), ('trust_gestion_recibo', 'Gestión de recibos(trustseguros)')), 'verbose_name': 'póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AddField(
            model_name='archivo',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DocumentType', verbose_name='Tipo de documento'),
        ),
    ]
