# Generated by Django 2.1.3 on 2020-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0138_auto_20201203_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='calc_alt',
            field=models.BooleanField(default=False, help_text='Al activar esta opción se invalida las configuraciones anteriores', verbose_name='Método de calculo alternativo'),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='cdp',
            field=models.PositiveIntegerField(default=0, verbose_name='coberturas daños propios'),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='csorcv',
            field=models.PositiveIntegerField(default=0, verbose_name='coberturas SOA'),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='sorcv',
            field=models.FloatField(default=0.0, verbose_name='SOA sin emisión'),
        ),
    ]
