# Generated by Django 2.1.3 on 2021-02-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0140_auto_20201210_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campain',
            options={'ordering': ['name'], 'verbose_name': 'campaña'},
        ),
    ]
