# Generated by Django 2.1.3 on 2021-04-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0144_tramite_remplaza_recibo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aseguradora',
            options={'ordering': ['code']},
        ),
    ]
