# Generated by Django 2.1.3 on 2021-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0145_auto_20210404_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoadicional',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
