# Generated by Django 2.1.3 on 2021-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0146_campoadicional_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campoadicional',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='pagocuota',
            options={'ordering': ['fecha_pago']},
        ),
        migrations.AlterField(
            model_name='poliza',
            name='cantidad_cuotas',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='f_pago',
            field=models.PositiveIntegerField(choices=[(1, 'Contado'), (2, 'Fraccionado')], null=True, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='m_pago',
            field=models.PositiveIntegerField(choices=[(1, 'Transferencia'), (2, 'Cheques'), (3, 'Depósitos'), (6, 'Tarjeta de Credito'), (4, 'Deducción por Nómina'), (6, 'Efectivo')], null=True, verbose_name='medio de pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='no_recibo',
            field=models.CharField(max_length=25, null=True, verbose_name='número de recibo'),
        ),
    ]
