# Generated by Django 2.1.3 on 2021-04-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0147_auto_20210416_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['fecha_vence']},
        ),
    ]
