# Generated by Django 2.1.3 on 2021-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0148_auto_20210416_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='email_cliente',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Contenido del correo de notificación del cliente'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estado_poliza',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pendiente'), (1, 'Activa'), (2, 'Vencida'), (3, 'Renovada'), (4, 'Cancelada'), (5, 'Anulada'), (6, 'No renovada')], default=0, null=True),
        ),
    ]
