# Generated by Django 2.1.3 on 2021-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0149_auto_20210908_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='notificacion_cliente',
            field=models.BooleanField(default=True, verbose_name='activar notificaciónes que se envian al cliente'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='email_cliente',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Contenido del correo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='email_notificacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='email para notificaciones de pólizas a vencer'),
        ),
    ]
