# Generated by Django 2.1.3 on 2021-09-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0150_auto_20210909_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='sub_tipo_tramite',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Inclusión'), (2, 'Exclusión'), (3, 'Renovación'), (4, 'Aumento de Suma'), (5, 'Disminución de suma'), (6, 'Cancelación'), (7, 'Modificación')], null=True),
        ),
    ]
