# Generated by Django 2.1.3 on 2021-10-20 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0151_tramite_sub_tipo_tramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario que registra'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='sub_tipo_tramite',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Inclusión'), (2, 'Exclusión'), (3, 'Renovación'), (4, 'Aumento de Suma'), (5, 'Disminución de suma'), (6, 'Cancelación'), (7, 'Modificación')], null=True, verbose_name='sub tipo de trámite'),
        ),
    ]
