# Generated by Django 2.1.3 on 2021-11-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0154_oportunity_user_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siniestro',
            options={'permissions': (('trust_siniestros', 'Siniestros(trustseguros)'),)},
        ),
        migrations.AlterModelOptions(
            name='siniestrotramite',
            options={'permissions': (('trust_siniestros_tramites', 'Trámites Siniestros(trustseguros)'),)},
        ),
    ]
