# Generated by Django 2.1.3 on 2021-11-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0155_auto_20211101_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('valor_eng', models.CharField(max_length=160)),
                ('valor_spa', models.CharField(max_length=160)),
                ('extended_info', models.TextField(max_length=600, verbose_name='información adicional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityTravel',
            fields=[
                ('iso', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('state', models.CharField(max_length=160, verbose_name='estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTravel',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyTravel',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanCategoryTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='nombre')),
                ('description', models.CharField(max_length=160, verbose_name='descripción')),
                ('languaje', models.CharField(max_length=3, verbose_name='lenguaje')),
                ('num_pas', models.PositiveSmallIntegerField(verbose_name='')),
                ('min_tiempo', models.PositiveSmallIntegerField(verbose_name='')),
                ('max_tiempo', models.PositiveSmallIntegerField(verbose_name='')),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='')),
                ('normal_age', models.PositiveSmallIntegerField(verbose_name='')),
                ('family_plan', models.CharField(max_length=1, verbose_name='es plan familiar?')),
                ('plan_local', models.CharField(max_length=1, verbose_name='es plan local?')),
                ('combo', models.CharField(max_length=1, verbose_name='es combo?')),
                ('modo_plan', models.CharField(max_length=1, verbose_name='modo del plan')),
                ('is_active', models.BooleanField(default=True)),
                ('plan_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PlanCategoryTravel', verbose_name='categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TerritoryTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='citytravel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CountryTravel'),
        ),
        migrations.AddField(
            model_name='benefittravel',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PlanTravel'),
        ),
    ]
