# Generated by Django 2.1.3 on 2021-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0156_auto_20211101_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytravel',
            name='iso',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
