# Generated by Django 2.1.3 on 2021-11-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0157_auto_20211101_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantravel',
            name='combo',
            field=models.CharField(max_length=1, null=True, verbose_name='es combo?'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='description',
            field=models.CharField(max_length=160, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='family_plan',
            field=models.CharField(max_length=1, null=True, verbose_name='es plan familiar?'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='max_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='max_tiempo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='min_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='min_tiempo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='modo_plan',
            field=models.CharField(max_length=1, null=True, verbose_name='modo del plan'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='normal_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='num_pas',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='plan_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PlanCategoryTravel', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='plan_local',
            field=models.CharField(max_length=1, null=True, verbose_name='es plan local?'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='title',
            field=models.CharField(max_length=160, null=True, verbose_name='nombre'),
        ),
    ]
