# Generated by Django 2.1.3 on 2021-11-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0158_auto_20211102_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciatravel',
            name='pais_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.CountryTravel'),
        ),
        migrations.AddField(
            model_name='asistenciatravel',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.PlanTravel'),
        ),
        migrations.AddField(
            model_name='asistenciatravel',
            name='territorio_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.TerritoryTravel'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='max_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='edad máxima'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='max_tiempo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='tiempo máximo'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='min_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='edad mínima'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='min_tiempo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='tiempo mínimo'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='normal_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='edad usual'),
        ),
        migrations.AlterField(
            model_name='plantravel',
            name='num_pas',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='número de pasajeros'),
        ),
    ]
