# Generated by Django 2.1.3 on 2021-11-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0160_auto_20211102_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengersTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='')),
                ('apellidos', models.CharField(max_length=150, verbose_name='')),
                ('telefono', models.CharField(max_length=150, verbose_name='')),
                ('correo', models.CharField(max_length=150, verbose_name='')),
                ('nacimiento', models.CharField(max_length=150, verbose_name='')),
                ('documento', models.CharField(max_length=150, verbose_name='')),
                ('observaciones_medicas', models.CharField(max_length=150, verbose_name='')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.AsistenciaTravel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
