# Generated by Django 2.1.3 on 2021-11-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0161_passengerstravel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciatravel',
            name='consideraciones_generales',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='backend.AsistenciaTravel'),
        ),
    ]
