# Generated by Django 2.1.3 on 2021-11-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0162_auto_20211102_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerstravel',
            name='apellidos',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='correo',
            field=models.CharField(max_length=150, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='documento',
            field=models.CharField(max_length=150, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='nacimiento',
            field=models.CharField(max_length=150, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='nombres',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='observaciones_medicas',
            field=models.CharField(max_length=150, verbose_name='observaciones médicas'),
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='telefono',
            field=models.CharField(max_length=150, verbose_name='teléfono'),
        ),
    ]
