# Generated by Django 2.1.3 on 2021-11-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0164_auto_20211102_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciatravel',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.CurrencyTravel'),
        ),
        migrations.AddField(
            model_name='asistenciatravel',
            name='tasa_cambio',
            field=models.FloatField(blank=True, null=True, verbose_name='tasa de cambio'),
        ),
    ]
