# Generated by Django 2.1.3 on 2021-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0166_auto_20211102_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytravel',
            name='id',
            field=models.BigIntegerField(null=True),
        ),
    ]
