# Generated by Django 2.1.3 on 2021-11-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0167_countrytravel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrytravel',
            name='id',
        ),
    ]
