# Generated by Django 2.1.3 on 2021-11-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0168_remove_countrytravel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciatravel',
            name='telefono_contacto',
            field=models.CharField(max_length=255, null=True, verbose_name='teléfono del contacto'),
        ),
    ]
