# Generated by Django 2.2 on 2022-05-25 12:28

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0169_asistenciatravel_telefono_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=14, null=True, verbose_name='número de identificación')),
                ('primer_nombre', models.CharField(blank=True, max_length=125, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=125, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=125, null=True, verbose_name='primer apellido')),
                ('apellido_materno', models.CharField(blank=True, max_length=125, null=True, verbose_name='segundo apellido')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('celular', models.CharField(blank=True, max_length=8, null=True)),
                ('email_personal', models.EmailField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles')),
                ('estado_civil', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Union de hecho libre')], null=True)),
                ('cropping', image_cropping.fields.ImageRatioField('foto', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='passengerstravel',
            name='documento',
            field=models.CharField(default='CDI', max_length=150, verbose_name='tipo de documento'),
        ),
    ]
