# Generated by Django 2.1.3 on 2021-11-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0169_asistenciatravel_telefono_contacto'),
        ('backend', '0165_auto_20211102_1526'),
    ]

    operations = [
    ]
