# Generated by Django 2.2 on 2022-05-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0170_merge_20211102_1910'),
        ('backend', '0171_recomendado_user'),
    ]

    operations = [
    ]
