# Generated by Django 2.2 on 2022-10-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0171_recomendado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='nombre')),
                ('color', models.CharField(default='#000000', max_length=65, verbose_name='color')),
                ('icon', models.CharField(default='fa fa-tag', max_length=65, verbose_name='icono')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
