# Generated by Django 2.2 on 2022-10-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0173_auto_20221014_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagseguimiento',
            options={'verbose_name': 'tag de seguimiento', 'verbose_name_plural': 'tags de seguimiento'},
        ),
        migrations.AlterField(
            model_name='tagseguimiento',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=65, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='tagseguimiento',
            name='icon',
            field=models.CharField(blank=True, default='fa fa-tag', max_length=65, null=True, verbose_name='icono'),
        ),
    ]
