# Generated by Django 2.2 on 2022-10-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0172_merge_20220525_1558'),
        ('backend', '0174_auto_20221014_2319'),
    ]

    operations = [
    ]
