# Generated by Django 2.2 on 2022-10-14 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0175_merge_20221014_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.TagSeguimiento'),
        ),
    ]
