# Generated by Django 2.1.3 on 2019-08-24 23:29

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiguedad', models.PositiveSmallIntegerField(default=0)),
                ('factor', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'año',
                'verbose_name_plural': 'Años de antiguedad',
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos')),
                ('cropping', image_cropping.fields.ImageRatioField('logo', '400x400', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='vista previa')),
                ('phone', models.CharField(blank=True, max_length=80, null=True, verbose_name='teléfono de contacto')),
                ('address', models.TextField(blank=True, max_length=600, null=True, verbose_name='dirección')),
                ('emision', models.FloatField(default=2.0, verbose_name='derecho de emision')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Descripción detallada')),
                ('suma_asegurada', models.FloatField(default=0.0, verbose_name='exceso')),
                ('emision', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Descripción detallada')),
                ('tipo_calculo', models.PositiveSmallIntegerField(choices=[(1, 'PRECIO FIJO'), (2, 'TASA PORCENTUAL'), (3, 'TASA PORMILLAR')], default=3)),
                ('tipo_cobertura', models.PositiveSmallIntegerField(choices=[(1, 'Básica'), (2, 'Ampliada'), (3, 'Adicional'), (4, 'Opcional')], default=1, verbose_name='variable de cobertura')),
                ('tipo_exceso', models.CharField(choices=[('0.0', '0.0'), ('valor_nuevo', 'Valor de Nuevo'), ('valor_depreciado', 'Valor Depreciado'), ('otro', 'Otro')], default='0.0', max_length=25, verbose_name='variable de calculo')),
                ('iva', models.BooleanField(default=True, verbose_name='aplica iva')),
            ],
            options={
                'verbose_name': 'cobertura',
                'verbose_name_plural': 'coberturas ofrecidas',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Descripción detallada')),
                ('suma_asegurada', models.FloatField(default=0.0, verbose_name='exceso')),
                ('tipo_exceso', models.CharField(choices=[('0.0', '0.0'), ('valor_nuevo', 'Valor de Nuevo'), ('valor_depreciado', 'Valor Depreciado'), ('otro', 'Otro')], default='0.0', max_length=25, verbose_name='variable de calculo')),
                ('tipo_calculo', models.PositiveSmallIntegerField(choices=[(1, 'PRECIO FIJO'), (2, 'TASA PORCENTUAL'), (3, 'TASA PORMILLAR')], default=3)),
                ('iva', models.BooleanField(default=True, verbose_name='aplica iva')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.Cobertura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=6, null=True)),
                ('nombres', models.CharField(max_length=300)),
                ('apellidos', models.CharField(max_length=300, null=True)),
                ('cedula', models.CharField(max_length=14, null=True, verbose_name='cédula')),
                ('email', models.EmailField(max_length=300, null=True)),
                ('tipo_auto', models.PositiveSmallIntegerField(choices=[(1, 'VEHICULO'), (2, 'MOTO')], default=1)),
                ('marca', models.CharField(max_length=65, null=True)),
                ('modelo', models.CharField(max_length=65, null=True)),
                ('anno', models.PositiveSmallIntegerField(null=True, verbose_name='año')),
                ('chasis', models.CharField(blank=True, max_length=125, null=True)),
                ('motor', models.CharField(blank=True, max_length=125, null=True)),
                ('valor_nuevo', models.FloatField(default=0.0, verbose_name='valor de nuevo')),
                ('aseguradora', models.ManyToManyField(to='seguros.Aseguradora', verbose_name='aseguradoras')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciónes',
            },
        ),
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_auto', models.PositiveSmallIntegerField(choices=[(1, 'VEHICULO'), (2, 'MOTO')], default=1)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla_depreciacion', to='seguros.Aseguradora')),
            ],
            options={
                'verbose_name': 'tabla',
                'verbose_name_plural': 'Tablas de Depreciación',
            },
        ),
        migrations.CreateModel(
            name='DetalleCobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('monto', models.FloatField(default=0.0)),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.Cobertura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.FloatField(default=0.0)),
                ('quota_seguro', models.FloatField(default=0.0)),
                ('available', models.BooleanField(default=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.Aseguradora')),
                ('costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='seguros.Costo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=25, null=True)),
                ('nombres', models.CharField(max_length=300)),
                ('apellidos', models.CharField(max_length=300, null=True)),
                ('cedula', models.CharField(max_length=14, null=True, verbose_name='cédula')),
                ('telefono', models.CharField(max_length=14, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(max_length=300, null=True)),
                ('tipo_auto', models.PositiveSmallIntegerField(choices=[(1, 'VEHICULO'), (2, 'MOTO')], default=1)),
                ('marca', models.CharField(max_length=65, null=True)),
                ('modelo', models.CharField(max_length=65, null=True)),
                ('anno', models.PositiveSmallIntegerField(null=True, verbose_name='año')),
                ('capacidad', models.CharField(max_length=65, null=True)),
                ('tonelaje', models.CharField(max_length=65, null=True)),
                ('chasis', models.CharField(blank=True, max_length=125, null=True)),
                ('motor', models.CharField(blank=True, max_length=125, null=True)),
                ('circulacion', models.CharField(blank=True, max_length=125, null=True)),
                ('vin', models.CharField(blank=True, max_length=125, null=True)),
                ('certificado', models.CharField(blank=True, max_length=125, null=True)),
                ('placa', models.CharField(blank=True, max_length=125, null=True)),
                ('uso', models.CharField(blank=True, max_length=125, null=True)),
                ('valor_nuevo', models.FloatField(default=0.0, verbose_name='valor de nuevo')),
                ('valor_depreciado', models.FloatField(default=0.0, verbose_name='valor de nuevo')),
                ('basica', models.FloatField(default=0.0)),
                ('amplia', models.FloatField(default=0.0)),
                ('adicional', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('emision', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('cuota', models.FloatField(default=0.0)),
                ('modo_pago', models.PositiveSmallIntegerField(choices=[(1, 'UN PAGO ANUAL'), (2, '12 CUOTAS MENSUALES')], default=1)),
                ('medios_pago', models.PositiveSmallIntegerField(choices=[(1, 'DÉBITO AUTOMÁTICO'), (2, 'DEPÓSITO REFERENCIADO')], default=1)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguros.Aseguradora')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
                ('available', models.BooleanField(default=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.Aseguradora')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='seguros.Cobertura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Descripción detallada')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=65)),
                ('modelo', models.CharField(max_length=65)),
                ('tipo', models.CharField(max_length=165, null=True)),
                ('clase', models.CharField(max_length=165, null=True)),
                ('anno', models.PositiveSmallIntegerField(verbose_name='año')),
                ('valor', models.FloatField(default=0.0)),
                ('chasis', models.CharField(blank=True, max_length=125, null=True)),
                ('motor', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'valor',
                'verbose_name_plural': 'valores de referencia',
            },
        ),
        migrations.CreateModel(
            name='ValorDepreciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annos', models.PositiveSmallIntegerField(default=0, verbose_name='años')),
                ('valor_nuevo', models.FloatField(default=0.0)),
                ('valor_depreciado', models.FloatField(default=0.0)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.Aseguradora')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='seguros.Cotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguros.Producto'),
        ),
        migrations.AddField(
            model_name='costo',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='seguros.Cotizacion'),
        ),
        migrations.AddField(
            model_name='cobertura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='seguros.Producto'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='cobertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.Cobertura'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='seguros.Poliza'),
        ),
        migrations.AddField(
            model_name='anno',
            name='depreciacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos', to='seguros.Depreciacion'),
        ),
        migrations.AlterUniqueTogether(
            name='valordepreciado',
            unique_together={('cotizacion', 'aseguradora')},
        ),
        migrations.AlterUniqueTogether(
            name='depreciacion',
            unique_together={('aseguradora', 'tipo_auto')},
        ),
    ]
