# Generated by Django 2.1.3 on 2019-12-17 20:55

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('imagen', image_cropping.fields.ImageCropField(upload_to='banners')),
                ('cropping', image_cropping.fields.ImageRatioField('imagen', '400x800', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='vista previa')),
            ],
            options={
                'verbose_name_plural': 'Publicidad',
            },
        ),
    ]
